import { Button } from './my-component/Button';
import { Input } from './my-component/Input';
import { Page } from './my-component/Page';
import { CheckboxInput } from './my-component/CheckboxInput';
import { ColorInput } from './my-component/ColorInput';
import { FileInput } from './my-component/FileInput';
import { Select } from './my-component/Select';
import { Dropdown } from './my-component/Dropdown';
import { Modal } from './my-component/Modal';
import { CalendarInput } from './my-component/CalendarInput';
export { Button, Page, Input, CheckboxInput, ColorInput, FileInput, Select, Dropdown, Modal, CalendarInput, };
