import { Button } from './my-component/Button';
import { InputTypeAWithoutIcon } from './my-component/InputTypeAWithoutIcon';
import { InputTypeAWithIcon } from './my-component/InputTypeAWithIcon';
import { Page } from './my-component/Page';
import { CheckboxInput } from './my-component/CheckboxInput';
import { ColorInput } from './my-component/ColorInput';
import { ColorInputV2 } from './my-component/ColorInputV2';
import { FileInput } from './my-component/FileInput';
import { Select } from './my-component/Select';
import { Dropdown } from './my-component/Dropdown';
import { Modal } from './my-component/Modal';
import { CalendarInput } from './my-component/CalendarInput';
import { ImageInput } from './my-component/ImageInput';
import { ButtonTypeAWithIcon } from './my-component/ButtonTypeAWithIcon';
import { ButtonTypeAWithoutIcon } from './my-component/ButtonTypeAWithoutIcon';
import { PaperA } from './components/PaperA';
export { Button, Page, InputTypeAWithIcon, InputTypeAWithoutIcon, CheckboxInput, ColorInput, ColorInputV2, FileInput, Select, Dropdown, Modal, CalendarInput, ImageInput, ButtonTypeAWithIcon, ButtonTypeAWithoutIcon, PaperA, };
